const express = require('express');
const auth = require('../middleware/authMiddleware');
const admin = require('../middleware/adminMiddleware');
const c = require('../controllers/adminController');
const router = express.Router();
router.use(auth, admin);
router.get('/users', c.users);
router.get('/verifications', c.verifications);
router.get('/statistics', c.statistics);
router.get('/users/:id', c.userDetail);
module.exports = router;
