import React, { useState } from 'react';
import { ShieldCheck, FileCheck2, UserRound, Sparkles, ArrowRight, RotateCcw } from 'lucide-react';
import { CameraCapture } from '../components/CameraCapture';
import { submitVerification } from '../services/api';

export function VerificationPage({ onComplete, onBack }) {
  const [step,setStep]=useState(1); const [document1,setDocument1]=useState(null); const [document2,setDocument2]=useState(null); const [selfie,setSelfie]=useState(null); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const run=async()=>{setLoading(true);setError('');try{const r=await submitVerification({document1,document2,selfie});setResult(r.verification);setStep(4);onComplete?.(r.verification);}catch(e){setError(e.message);}finally{setLoading(false);}};
  return <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12 space-y-6 animate-fadeIn">
    <div className="bg-gradient-to-r from-slate-950 via-brand-950 to-brand-900 rounded-3xl p-7 sm:p-10 text-white shadow-xl"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-white/10 flex items-center justify-center"><ShieldCheck className="w-6 h-6 text-amber-300"/></div><div><div className="text-[10px] font-black tracking-widest text-blue-200 uppercase">AI Identity Verification</div><h1 className="text-3xl font-black">Verify your identity securely</h1></div></div><p className="mt-4 text-sm text-blue-100 max-w-3xl">Capture your identity document and a live selfie. The prototype sends both to the verification service for OCR and face comparison, then stores the verification result.</p></div>
    <div className="grid grid-cols-4 gap-2">{['Documents','Selfie','AI Analysis','Result'].map((x,i)=><div key={x} className={`p-3 rounded-xl text-center text-[11px] font-bold ${step===i+1?'bg-brand-700 text-white':'bg-slate-100 text-slate-500'}`}>{i+1}. {x}</div>)}</div>
    {step===1&&<div className="bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 space-y-5"><div><h2 className="text-2xl font-black">Capture identity document</h2><p className="text-xs text-slate-500 mt-1">Use a clear, synthetic/demo identity document for the hackathon prototype.</p></div><CameraCapture title="Primary identity document" onCapture={setDocument1}/><div className="flex items-center gap-3"><label className="text-xs font-bold text-slate-600">Optional second document</label><input type="file" accept="image/*" onChange={e=>setDocument2(e.target.files?.[0]||null)} className="text-xs"/></div><button disabled={!document1} onClick={()=>setStep(2)} className="w-full py-3 rounded-xl bg-brand-700 disabled:bg-slate-300 text-white text-xs font-bold flex justify-center gap-2 items-center">Continue to selfie <ArrowRight className="w-4 h-4"/></button></div>}
    {step===2&&<div className="bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 space-y-5"><div><h2 className="text-2xl font-black">Take a live selfie</h2><p className="text-xs text-slate-500 mt-1">Keep your face centered and well lit.</p></div><CameraCapture mode="selfie" title="Live selfie" onCapture={setSelfie}/><div className="flex gap-3"><button onClick={()=>setStep(1)} className="flex-1 py-3 rounded-xl bg-slate-100 text-slate-700 text-xs font-bold">Back</button><button disabled={!selfie} onClick={()=>setStep(3)} className="flex-1 py-3 rounded-xl bg-brand-700 disabled:bg-slate-300 text-white text-xs font-bold">Run AI verification</button></div></div>}
    {step===3&&<div className="bg-white rounded-3xl border border-slate-200 p-10 text-center"><Sparkles className="w-12 h-12 text-brand-700 mx-auto animate-pulse"/><h2 className="text-2xl font-black mt-4">Ready for AI analysis</h2><p className="text-xs text-slate-500 mt-2">OCR + document checks + face comparison</p>{error&&<div className="mt-4 text-xs text-rose-700 bg-rose-50 p-3 rounded-xl">{error}</div>}<button disabled={loading} onClick={run} className="mt-6 px-6 py-3 rounded-xl bg-brand-700 text-white text-xs font-bold">{loading?'Analyzing...':'Start verification'}</button></div>}
    {step===4&&result&&<div className="bg-white rounded-3xl border border-slate-200 p-6 sm:p-8"><div className="flex items-center gap-3"><div className={`w-12 h-12 rounded-2xl flex items-center justify-center ${result.status==='verified'?'bg-emerald-100 text-emerald-700':'bg-rose-100 text-rose-700'}`}><ShieldCheck className="w-6 h-6"/></div><div><h2 className="text-2xl font-black">{result.status==='verified'?'Identity Verified':'Verification Failed'}</h2><p className="text-xs text-slate-500">{result.aiDetails?.message||result.failureReason||'Verification completed'}</p></div></div><div className="grid sm:grid-cols-3 gap-4 mt-7">{[['Document Check',result.documentMatch],['Data Match',result.dataMatch],['Face Match',result.faceMatch]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 p-5"><div className="text-xs font-bold text-slate-500">{label}</div><div className={`mt-2 text-lg font-black ${value?'text-emerald-700':'text-rose-700'}`}>{value?'PASS':'FAIL'}</div></div>)}</div><div className="mt-5 rounded-2xl bg-slate-50 p-5"><div className="text-xs font-bold text-slate-500">Verification confidence</div><div className="text-3xl font-black text-brand-900 mt-1">{result.confidenceScore != null ? Math.round(result.confidenceScore*100)+'%' : '—'}</div></div><button onClick={()=>{setStep(1);setResult(null);setDocument1(null);setSelfie(null);}} className="mt-6 px-4 py-2.5 rounded-xl bg-slate-100 text-slate-700 text-xs font-bold flex items-center gap-2"><RotateCcw className="w-4 h-4"/> Start another verification</button></div>}
    <div className="text-[10px] text-slate-400 text-center">Prototype only — do not upload real Aadhaar/PAN or other sensitive identity documents.</div>
  </div>;
}
